### ISSUE TITLE
Order files by modification date

### ISSUE THREAD

**Issue by gorman42** [moisesmcardona/GoogleDriveUploadTool#10]
I'd like for the tool to allow to order files by the criteria available in the web interface. Is this possible?

**Comment by moisespr123** [comment]
Yes. The next version will feature a "sort by..." menu along other nice stuff! Currently, in the code, it is specified to sort by name.

`listRequest.OrderBy = "name"`

Thanks for your suggestion and look forward for future releases!

**Comment by moisespr123** [comment]
Added in the latest commit. Release will come as soon as I finish implementing some additional features.

**Comment by gorman42** [comment]
Great! Thank you so much! The program is proving extremely helpful for me. Thanks for continued development.

**Comment by moisespr123** [comment]
v1.8 has been released. Sort is available in Options -> Sort By
