### ISSUE TITLE
Make the tool window "really" resizable

### ISSUE THREAD

**Issue by gorman42** [moisesmcardona/GoogleDriveUploadTool#11]
Currently when the window is resized, it just adds blank grey space. It would be nice to be able to make the window bigger and have more space for file lists.

I hope this can be implemented. :)

**Comment by moisespr123** [comment]
This is in the TODO list 🙂

**Comment by gorman42** [comment]
Cool!

**Comment by moisespr123** [comment]
v1.8 has been released and the GUI is now resizable 🙂
