### ISSUE TITLE
Error at exe opening

### ISSUE THREAD

**Issue by f-liva** [moisesmcardona/GoogleDriveUploadTool#18]
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in Google_Drive_Uploader.GoogleDriveClass.GetData(String folderId, String OrderBy, Boolean goingBack, Boolean refreshing)
   in Google_Drive_Uploader.Form1.EnterFolder(String location, Boolean refreshing)
   in Google_Drive_Uploader.Form1.Form1_Load(Object sender, EventArgs e)
   in System.EventHandler.Invoke(Object sender, EventArgs e)
   in System.Windows.Forms.Form.OnLoad(EventArgs e)
   in System.Windows.Forms.Form.OnCreateControl()
   in System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   in System.Windows.Forms.Control.CreateControl()
   in System.Windows.Forms.Control.WmShowWindow(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.Form.WmShowWindow(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3815.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Google Drive Uploader1
    Versione assembly: 1.11.1.0
    Versione Win32: 1.11.1.0
    Base di codice: file:///C:/Users/fede9/Desktop/Google.Drive.Upload.Tool.v1.11.1/Google%20Drive%20Uploader1.exe
----------------------------------------
Microsoft.VisualBasic
    Versione assembly: 10.0.0.0
    Versione Win32: 14.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3801.0 built by: NET48REL1LAST_B
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3815.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3815.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Microsoft.GeneratedCode
    Versione assembly: 1.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Google.Apis.Drive.v3
    Versione assembly: 1.40.2.1649
    Versione Win32: 1.40.2.1649
    Base di codice: file:///C:/Users/fede9/Desktop/Google.Drive.Upload.Tool.v1.11.1/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Versione assembly: 1.40.2.0
    Versione Win32: 1.40.2.0
    Base di codice: file:///C:/Users/fede9/Desktop/Google.Drive.Upload.Tool.v1.11.1/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Versione assembly: 1.40.2.0
    Versione Win32: 1.40.2.0
    Base di codice: file:///C:/Users/fede9/Desktop/Google.Drive.Upload.Tool.v1.11.1/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Versione assembly: 1.40.2.0
    Versione Win32: 1.40.2.0
    Base di codice: file:///C:/Users/fede9/Desktop/Google.Drive.Upload.Tool.v1.11.1/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Accessibility
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by moisespr123** [comment]
Try v1.14.
