### ISSUE TITLE
Stuck at 0% Retrying...

### ISSUE THREAD

**Issue by princhonzik** [moisesmcardona/GoogleDriveUploadTool#20]
I use the tool to upload large files and I enjoy the possibility to close the program, turn off the pc and resume when I’m online again. Sometimes, immediately when I click resume, instead of the correct values, it shows 0 MB and 0 % and says "Retrying..." forever. This seems to happen randomly. As of now, however, I have not been able to upload a 70 GB file correctly in one go, with some three or four tries. The only way I have found to get the program out of this state is to start a new upload from zero.

Any idea how to look for the culprit?

![ohnozero](https://user-images.githubusercontent.com/57719932/69560125-89909680-0fab-11ea-9699-5d81efe67f3f.jpg)

**Comment by moisespr123** [comment]
Hi,

This usually happens if the machine or connection has been offline for hours. I think that Google removes the temporary upload on their servers after a few hours if there has not been any activity.

**Comment by princhonzik** [comment]
This did not cross my mind at first as the time after which it happens varies, but yes, it makes sense. Thanks!
