### ISSUE TITLE
Application freezes

### ISSUE THREAD

**Issue by svolchkov** [moisesmcardona/GoogleDriveUploadTool#21]
Trying to use the application on Windows 10. The first time it uploaded a handful of files and then froze. The second time it froze straight away upon clicking Upload. Not usable.

**Comment by svolchkov** [comment]
It did work after all when selecting a folder via the File menu. But it took about 5 minutes to load about 50 files totaling under 4Mb on a 350 Mbit/s upload network. I was planning to use the program to load 200k files totalling 100Gb but that apparently would be out of the question with this app.

**Comment by moisespr123** [comment]
I'm unable to reproduce this issue.
