### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by SaLiXeM** [moisesmcardona/GoogleDriveUploadTool#7]
Hello,

The program generates an error at start. Though I can press continue and bring up the main window, But it won't ask for my credentials, or open a web page so I can login to my Drive account.

![image](https://user-images.githubusercontent.com/26151458/34315982-581de77c-e7a0-11e7-81de-abc7cb4a0afe.png)

**Comment by moisespr123** [comment]
Hi,

Please follow the steps mentioned in "Step 1" in this document: https://developers.google.com/drive/v3/web/quickstart/dotnet

It's very important you place the "client_secret.json" file in the same folder where the software is located.

**Comment by moisespr123** [comment]
I'm closing this issue as this is documented in the Readme.

The next release will check if this file exists. If not, it will prompt you to follow the steps provided in the comment above. This check is already in the source code.
