### ISSUE TITLE
Automatic Upload

### ISSUE THREAD

**Issue by MrTwIXx** [moisesmcardona/GoogleDriveUploadTool#9]
Hey there,

Will this programm start the upload automatic when a new file will add to a folder?
So will this toll scan the folder?

Thanks

**Comment by moisespr123** [comment]
Hi,

If you initially started the upload and later add more files and folders
while the uploads are still ongoing, then it will automatically upload the
rest of the files.

If you mean starting the upload as soon as you drag and drop files without
actually pressing the upload button, then no. You'll need to press the
upload button to initiate the uploads.

**Comment by MrTwIXx** [comment]
Hey there,

I mean it without pressing the upload button. Do you know a program witch can do this?

Thanks

**Comment by moisespr123** [comment]
Not that I know, unless you use the Google Drive web interface or a desktop
software that mounts your account as a drive like Net Drive.

Either way, this seems like a nice feature request 😁

**Comment by MrTwIXx** [comment]
Of course, because I need that for my automation :)

**Comment by moisespr123** [comment]
The feature has been implemented in the code and will be available in the next release.

**Comment by MrTwIXx** [comment]
Nice Thank you very much

**Comment by MrTwIXx** [comment]
When will you release the new version?

**Comment by moisespr123** [comment]
I want to add an extra feature to it and then it will be released. Maybe during these days or by the end of the month/start of the next month, it will get released, but I'll try to release it as soon as possible

**Comment by MrTwIXx** [comment]
Any news here?

**Comment by moisespr123** [comment]
Hi @MrTwIXx ,

Sorry for the delay. v1.7.1 has been released. Please check it out and let me know if it works for you.

Thanks and have a nice day!

**Comment by MrTwIXx** [comment]
I will test it today evening, but I think it isn't that what I want. I need something, when a new file is moved to a specific folder the upload starts automaticly and when the file is uploaded it delete it automaticly. SO your tool has to monitor a specific folder. Is that possible?

Thanks

**Comment by moisespr123** [comment]
You must be in a folder to upload files. This could be any folder, or it can simply be the root of your drive. It will start the upload as soon as you drag a file/folder into the folder shown in the folder view. The files are not deleted, and I think it's best this way, because if a file fails uploads or uploads corrupted (This is why the app has MD5 hashes), then you would loose the original file while having the backed up copy in the cloud.

**Comment by MrTwIXx** [comment]
Ok thanks, Will test it in the evening :)

**Comment by darkzbaron** [comment]
Any chance to make the uploads start automatically at program start when there is something in the queue? Thanks for the great program by the way!
